### ISSUE TITLE
Can't work with electron 1.4.1 drag app windows

### ISSUE THREAD

**Issue by stellar2016** [styoe/lacus-one#1]
![image](https://cloud.githubusercontent.com/assets/22653489/19143448/99568e64-8bd6-11e6-9929-2a77522a6937.png)

![image](https://cloud.githubusercontent.com/assets/22653489/19143421/6801cfd6-8bd6-11e6-90a6-34709b19e47d.png)

**Comment by styoe** [comment]
Sorry, i need to update the package json and write some docs about this project, hopefully in the next week i will find enough time to finish this. In the meantime, you can install the missing module from npm manually, there are 2 npm scripts for webpack, one for building, the other is a dev server, and two npm scripts for starting the app. One for windows, and default start for linux env.

**Comment by stellar2016** [comment]
@styoe thanks for your reply. after install webpack use npm like this:
![image](https://cloud.githubusercontent.com/assets/22653489/19144528/a98255f6-8bdc-11e6-8a93-de8c5f8b2f15.png)
the error still occurs. pls tell me how to do step by step.
thanks any way.

**Comment by styoe** [comment]
Hi, i updated the docs, so pls try following the steps in the installation part

**Comment by styoe** [comment]
closing for now
